# Generated by Django 5.1.5 on 2025-02-04 06:38

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, help_text='Enter main cast members', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='United States', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'General Audience'), ('PG', 'Parental Guidance'), ('PG-13', 'Parental Guidance for children under 13'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], default='PG', max_length=5),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AddField(
            model_name='review',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.genre'),
        ),
    ]
